# Generated by Django 5.2.16 on 2026-07-20 17:33

import datetime
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presupuesto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FondoAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_disponible', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fondo_ahorro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fondo de ahorro',
                'verbose_name_plural': 'Fondos de ahorro',
            },
        ),
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('monto_inicial', models.DecimalField(decimal_places=0, max_digits=14)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida (pendiente cierre)'), ('ganancia', 'Cerrada con ganancia'), ('perdida', 'Cerrada con pérdida'), ('neutral', 'Cerrada sin cambio'), ('en_curso', 'En curso (plazo extendido)')], default='activa', max_length=20)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inversión',
                'verbose_name_plural': 'Inversiones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoPatrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada_derivacion', 'Entrada por derivación'), ('entrada_sobrante', 'Entrada por sobrante de ciclo'), ('retiro', 'Retiro de ahorro'), ('inversion_salida', 'Salida a inversión'), ('inversion_retorno', 'Retorno de inversión'), ('ganancia', 'Ganancia de inversión'), ('perdida_capital', 'Pérdida de capital')], max_length=30)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=14)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_patrimonio', to='presupuesto.ciclomensual')),
                ('fondo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='ahorros.fondoahorro')),
                ('inversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_patrimonio', to='ahorros.inversion')),
                ('movimiento_presupuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_patrimonio', to='presupuesto.movimiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_patrimonio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de patrimonio',
                'verbose_name_plural': 'Movimientos de patrimonio',
                'ordering': ['-fecha'],
            },
        ),
    ]
