# Generated by Django 5.2.16 on 2026-07-21 02:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inversion',
            name='rendimiento_esperado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Rendimiento esperado (% anual)'),
        ),
        migrations.AddField(
            model_name='inversion',
            name='tipo_activo',
            field=models.CharField(choices=[('acciones', 'Acciones'), ('cripto', 'Criptomonedas'), ('fondos', 'Fondos indexados'), ('inmobiliario', 'Bienes raíces'), ('renta_fija', 'Renta fija / CDT'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo de activo'),
        ),
        migrations.CreateModel(
            name='MetaAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('icono', models.CharField(choices=[('fa-shield-halved', 'Fondo de emergencia'), ('fa-umbrella-beach', 'Vacaciones / Viaje'), ('fa-laptop', 'Tecnología'), ('fa-car', 'Vehículo'), ('fa-house', 'Vivienda / Hogar'), ('fa-graduation-cap', 'Educación'), ('fa-gift', 'Regalo / Evento'), ('fa-piggy-bank', 'General')], default='fa-piggy-bank', max_length=40)),
                ('color', models.CharField(default='#10B981', max_length=7)),
                ('monto_objetivo', models.DecimalField(decimal_places=0, max_digits=14)),
                ('saldo_actual', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14)),
                ('fecha_objetivo', models.DateField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('creada', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_ahorro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta de ahorro',
                'verbose_name_plural': 'Metas de ahorro',
                'ordering': ['completada', '-creada'],
            },
        ),
        migrations.CreateModel(
            name='DepositoMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=14)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to='ahorros.metaahorro')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
