from django.urls import path

from presupuesto import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('configuracion/', views.configuracion_inicial, name='configuracion_inicial'),
    path('configuracion/editar/', views.configuracion_editar, name='configuracion_editar'),
    path('perfil/', views.perfil, name='perfil'),
    path('confirmar-ciclo/', views.confirmar_ciclo, name='confirmar_ciclo'),
    path('ocultar-banner-pago/', views.ocultar_banner_pago, name='ocultar_banner_pago'),
    path('gasto/', views.registrar_gasto, name='registrar_gasto'),
    path('gasto/<int:gasto_id>/editar/', views.editar_gasto, name='editar_gasto'),
    path('gasto/<int:gasto_id>/eliminar/', views.eliminar_gasto, name='eliminar_gasto'),
    path('ingreso/', views.registrar_ingreso, name='registrar_ingreso'),
    path('envio-ahorro/', views.registrar_envio_ahorro, name='registrar_envio_ahorro'),
    path('cerrar-ciclo/', views.cerrar_ciclo_view, name='cerrar_ciclo'),
    path('historico/', views.historico_meses, name='historico_meses'),
    path('historico/pdf/', views.historico_pdf, name='historico_pdf'),
    path('ciclo/<int:pk>/', views.detalle_ciclo, name='detalle_ciclo'),
    path('categorias/', views.categorias_lista, name='categorias_lista'),
    path('categorias/crear/', views.categoria_crear, name='categoria_crear'),
    path('gastos-fijos/', views.gastos_fijos_lista, name='gastos_fijos_lista'),
    path('gastos-fijos/crear/', views.gasto_fijo_crear, name='gasto_fijo_crear'),
    path('gastos-fijos/<int:pk>/editar/', views.gasto_fijo_editar, name='gasto_fijo_editar'),
    path('gastos-fijos/<int:pk>/eliminar/', views.gasto_fijo_eliminar, name='gasto_fijo_eliminar'),
    path('gastos-fijos/<int:pk>/toggle/', views.gasto_fijo_toggle_activa, name='gasto_fijo_toggle'),
    path('calendario/', views.calendario_view, name='calendario'),
    path('calendario/crear/', views.crear_evento_calendario, name='crear_evento_calendario'),
    path('widgets/personizar/', views.personalizar_widgets, name='personalizar_widgets'),
    path('backup/', views.backup_gestion, name='backup_gestion'),
    path('backup/descargar/', views.backup_descargar, name='backup_descargar'),
    path('backup/restaurar/', views.backup_restaurar, name='backup_restaurar'),
    path('tutorial/completar/', views.completar_tutorial, name='completar_tutorial'),
]
