# Generated by Django 5.2.16 on 2026-07-20 17:33

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
                'unique_together': {('usuario', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='CicloMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('etiqueta', models.CharField(max_length=80)),
                ('salario_ciclo', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado'), ('pendiente', 'Pendiente de confirmación')], default='activo', max_length=12)),
                ('sobrante_transferido', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ciclo mensual',
                'verbose_name_plural': 'Ciclos mensuales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_base', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14, verbose_name='Salario base mensual')),
                ('dia_corte', models.PositiveSmallIntegerField(default=30, verbose_name='Día de corte/pago')),
                ('configurado', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de usuario',
                'verbose_name_plural': 'Configuraciones de usuario',
            },
        ),
        migrations.CreateModel(
            name='GastoFijoPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=14)),
                ('activa', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_fijos', to='presupuesto.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_fijos_plantilla', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto fijo (plantilla)',
                'verbose_name_plural': 'Gastos fijos (plantillas)',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso adicional'), ('gasto', 'Gasto'), ('envio_ahorro', 'Envío a ahorro'), ('inyeccion', 'Inyección de ahorro')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=14)),
                ('descripcion', models.CharField(max_length=300)),
                ('es_gasto_fijo', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='presupuesto.categoria')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='presupuesto.ciclomensual')),
                ('plantilla_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_generados', to='presupuesto.gastofijoplantilla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
