# Generated by Django 5.2.16 on 2026-07-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionusuario',
            name='ha_visto_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
