# Generated by Django 5.2.16 on 2026-07-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0002_configuracionusuario_ha_visto_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionusuario',
            name='dias_plazo_tolerancia',
            field=models.IntegerField(default=3, verbose_name='Días de plazo/tolerancia'),
        ),
    ]
