# Generated by Django 5.2.16 on 2026-07-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0003_configuracionusuario_dias_plazo_tolerancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionusuario',
            name='moneda',
            field=models.CharField(default='COP', max_length=3, verbose_name='Moneda de visualización'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='pagado',
            field=models.BooleanField(default=True, verbose_name='Pagado'),
        ),
    ]
