# Generated by Django 5.2.16 on 2026-07-21 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0004_configuracionusuario_moneda_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gastofijoplantilla',
            name='fecha_ultima_aplicacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de última aplicación'),
        ),
        migrations.AddField(
            model_name='gastofijoplantilla',
            name='frecuencia',
            field=models.CharField(choices=[('mensual', 'Cada mes'), ('bimensual', 'Cada 2 meses'), ('trimestral', 'Cada 3 meses'), ('semestral', 'Cada 6 meses'), ('anual', 'Cada año')], default='mensual', max_length=12, verbose_name='Frecuencia de repetición'),
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('pago', 'Pago'), ('recordatorio', 'Recordatorio'), ('cumpleanos', 'Cumpleaños'), ('otro', 'Otro')], default='otro', max_length=15)),
                ('monto', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Monto (opcional)')),
                ('repetir_anualmente', models.BooleanField(default=False)),
                ('completado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_calendario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de calendario',
                'verbose_name_plural': 'Eventos de calendario',
                'ordering': ['fecha', 'titulo'],
            },
        ),
    ]
