# Generated by Django 5.2.16 on 2026-07-21 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0005_gastofijoplantilla_fecha_ultima_aplicacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionusuario',
            options={},
        ),
        migrations.AddField(
            model_name='configuracionusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de perfil'),
        ),
        migrations.CreateModel(
            name='WidgetConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widgets_activos', models.JSONField(default=list, verbose_name='Widgets activos y orden')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='widget_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de widgets',
                'verbose_name_plural': 'Configuraciones de widgets',
            },
        ),
    ]
