# Generated by Django 5.2.16 on 2026-07-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0006_alter_configuracionusuario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionusuario',
            options={'verbose_name': 'Configuración de usuario', 'verbose_name_plural': 'Configuraciones de usuario'},
        ),
    ]
