# Generated by Django 5.2.16 on 2026-07-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0007_alter_configuracionusuario_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionusuario',
            name='foto_perfil',
        ),
    ]
