# Generated by Django 5.2.16 on 2026-07-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0008_remove_configuracionusuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de perfil'),
        ),
    ]
