# Generated by Django 5.2.16 on 2026-07-21 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0009_configuracionusuario_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionusuario',
            name='foto_perfil',
        ),
    ]
